"""Regression replay of the V1 `example.com` / domain investigation through the
V3 raw/analysis split. Repeatable: run after any change to collect.py /
graph_commit.py / the graph layer.

It verifies the SEPARATION the design depends on:
  Part A - collection (collect.py) runs tools + logs raw, and writes NO graph.
  Part B - graph_commit.py builds the graph from supervisor-tiered findings, and
           the three confidence tiers (confirmed/probable/possible) actually render.

Usage:  python tests/replay_domain.py
Exit code 0 = all checks pass.
"""
import json
import shutil
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

from src.core.state import create_investigation
from src.logger.investigation_log import InvestigationLogger
from src.tools.collect import collect_all
from src.tools import graph_commit

PASS, FAIL = "[PASS]", "[FAIL]"
failures = []


def check(cond, msg):
    print(f"{PASS if cond else FAIL} {msg}")
    if not cond:
        failures.append(msg)


def main():
    print("=== V3 regression replay: example.com / domain ===\n")

    # --- Setup: fresh investigation workspace ---
    state = create_investigation("example.com", "domain")
    case_id, case_dir = state["case_id"], Path(state["case_dir"])
    log_file, graph_file = state["log_file"], state["graph_file"]
    graph_html = state["graph_html"]
    InvestigationLogger(log_file).init_log(case_id, "example.com", "domain")
    print(f"Workspace: {case_dir}\n")

    # ---------- Part A: collection writes NO graph ----------
    print("--- Part A: gatherer collection (collect.py) ---")
    results = collect_all("example.com", "domain", log_file)
    tool_names = [r["tool"] for r in results]
    n_ok = sum(1 for r in results if r["result"].get("success"))
    n_entities = sum(len(r["result"].get("entities_found", [])) for r in results)
    print(f"Ran {len(results)} tools: {', '.join(tool_names)}")
    print(f"  successful: {n_ok}/{len(results)} | raw entities returned: {n_entities}")

    check(len(results) > 0, "collection ran at least one tool")
    check(not Path(graph_file).exists(),
          "NO graph.json written during collection (separation holds)")
    check(Path(log_file).exists() and Path(log_file).stat().st_size > 0,
          "raw output logged to investigation.md (audit trail)")

    # ---------- Part B: supervisor builds the tiered graph ----------
    print("\n--- Part B: supervisor graph_commit.py ---")
    # Build findings from real collected entities; tier by corroboration.
    source_count = {}
    entity_meta = {}
    for r in results:
        for e in r["result"].get("entities_found", []):
            key = (e["value"], e["entity_type"])
            source_count[key] = source_count.get(key, 0) + 1
            entity_meta[key] = e

    findings = {"entities": [
        {"value": "example.com", "type": "domain", "tool": "seed",
         "confidence": "confirmed", "citation": "investigation seed", "depth": 0}
    ], "relationships": []}

    for (value, etype), n in source_count.items():
        conf = "confirmed" if n >= 2 else "probable"  # corroborated -> strong
        e = entity_meta[(value, etype)]
        findings["entities"].append({
            "value": value, "type": etype, "tool": e.get("source_tool", "collect"),
            "confidence": conf, "citation": e.get("source_citation", ""), "depth": 1})
        findings["relationships"].append({
            "source_value": "example.com", "source_type": "domain",
            "target_value": value, "target_type": etype,
            "relationship": "related_to", "tool": e.get("source_tool", "collect"),
            "confidence": conf, "citation": e.get("source_citation", "")})

    out = graph_commit.commit(findings, graph_file, graph_html, case_id)
    print(f"committed: {out['entities_added']} entities, {out['relationships_added']} relationships")
    if out["warnings"]:
        print(f"  warnings: {out['warnings']}")

    check(Path(graph_file).exists(), "graph.json created by graph_commit")
    check(Path(graph_html).exists(), "graph.html regenerated by graph_commit")
    gdata = json.loads(Path(graph_file).read_text(encoding="utf-8"))
    check(len(gdata.get("nodes", [])) >= 1, "graph has at least the seed node")
    confs = {n.get("confidence") for n in gdata["nodes"]}
    check(confs.issubset({"confirmed", "probable", "possible"}),
          f"all node confidences are valid tiers (saw: {sorted(confs)})")

    # ---------- Part C: all three tiers render distinctly ----------
    print("\n--- Part C: 3-tier rendering check (isolated) ---")
    scratch = case_dir / "_tiertest.json"
    scratch_html = case_dir / "_tiertest.html"
    tier_spec = {"entities": [
        {"value": "strong.example", "type": "domain", "tool": "t", "confidence": "confirmed", "depth": 1},
        {"value": "likely.example", "type": "domain", "tool": "t", "confidence": "probable", "depth": 1},
        {"value": "weak.example", "type": "domain", "tool": "t", "confidence": "possible", "depth": 1},
    ], "relationships": [
        {"source_value": "strong.example", "source_type": "domain", "target_value": "weak.example",
         "target_type": "domain", "relationship": "maybe_linked", "tool": "t", "confidence": "possible"},
    ]}
    graph_commit.commit(tier_spec, str(scratch), str(scratch_html), "TIERTEST")
    td = json.loads(scratch.read_text(encoding="utf-8"))
    tiers_present = {n["confidence"] for n in td["nodes"]}
    check(tiers_present == {"confirmed", "probable", "possible"},
          f"all three tiers stored in graph ({sorted(tiers_present)})")
    html = scratch_html.read_text(encoding="utf-8")
    check("borderDashes" in html, "weak nodes render with dashed borders in HTML")
    check("badge-possible" in html, "HTML carries the 3-tier badge styling")
    # cleanup scratch tier-test artifacts
    scratch.unlink(missing_ok=True)
    scratch_html.unlink(missing_ok=True)

    # ---------- Verdict ----------
    print("\n=== RESULT ===")
    if failures:
        print(f"{FAIL} {len(failures)} check(s) failed:")
        for f in failures:
            print(f"   - {f}")
        return 1
    print(f"{PASS} all checks passed. Replayed case: {case_id}")
    print(f"Artifacts in: {case_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
