from datetime import datetime, timezone
from pathlib import Path


def generate_cti_report(
    case_id: str,
    seed_value: str,
    seed_type: str,
    bluf: str,
    findings: list[dict],
    tools_used: list[str],
    entity_table: list[dict],
    implications: str,
    investigation_log_summary: str,
    total_entities: int,
    total_relationships: int,
    duration_minutes: int,
    output_path: str,
):
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    findings_md = ""
    for i, f in enumerate(findings, 1):
        findings_md += f"{i}. **{f.get('title', 'Finding')}** - {f.get('description', '')} [Source: {f.get('source', 'unknown')}, Confidence: {f.get('confidence', 'unknown')}]\n"

    entity_rows = ""
    for e in entity_table[:50]:
        entity_rows += f"| `{e.get('value', '')[:40]}` | {e.get('type', '')} | {e.get('source', '')} | {e.get('confidence', '')} | {e.get('depth', '')} |\n"

    report = f"""# Cyber Threat Intelligence Report

| Field | Value |
|-------|-------|
| **Case ID** | {case_id} |
| **Classification** | TLP:CLEAR |
| **Date** | {now} |
| **Initial Seed** | `{seed_value}` ({seed_type}) |

---

## BLUF (Bottom Line Up Front)

{bluf}

---

## Significant Findings

{findings_md if findings_md else "No significant findings to report."}

---

## Investigation Method

- **Initial Seed:** `{seed_value}` (type: {seed_type})
- **Tools Used:** {', '.join(tools_used) if tools_used else 'None'}
- **Total Entities Discovered:** {total_entities}
- **Total Relationships Mapped:** {total_relationships}
- **Investigation Duration:** ~{duration_minutes} minutes

### Pivot Chain Summary

{investigation_log_summary}

---

## Entity Summary

| Entity | Type | Source | Confidence | Depth |
|--------|------|--------|------------|-------|
{entity_rows if entity_rows else "| (none) | - | - | - | - |"}

---

## Relationship Map

![Investigation Graph](./graph.png)

[Open Interactive Graph](./graph.html)

---

## Implications

{implications if implications else "No implications assessed - insufficient data or investigation scope."}

---

*Generated by OSINT Investigator | Case: {case_id} | {now}*
*This report contains only findings supported by tool output evidence. No speculative analysis included.*
"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    return output_path
