from datetime import datetime, timezone
from pathlib import Path

from src.graph.confidence import humanize as _conf_human


def _md_cell(value, width: int = 160) -> str:
    """Make a value safe for a markdown table cell (B5): escape pipes so they don't
    break the table, flatten newlines, and cap absurd widths (no lossy 40-char chop)."""
    s = str(value if value is not None else "").replace("|", "\\|")
    s = s.replace("\r", " ").replace("\n", " ").strip()
    if width and len(s) > width:
        s = s[:width - 1] + "…"
    return s


def generate_cti_report(
    case_id: str,
    seed_value: str,
    seed_type: str,
    bluf: str,
    findings: list[dict],
    tools_used: list[str],
    entity_table: list[dict],
    implications: str,
    investigation_log_summary: str,
    total_entities: int,
    total_relationships: int,
    duration_minutes: int,
    output_path: str,
    relationships: list[dict] | None = None,
):
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    findings_md = ""
    for i, f in enumerate(findings, 1):
        findings_md += (f"{i}. **{_md_cell(f.get('title', 'Finding'))}** - "
                        f"{f.get('description', '')} "
                        f"[Source: {f.get('source', 'unknown')}, "
                        f"Confidence: {_conf_human(f['confidence']) if f.get('confidence') else 'unknown'}]\n")

    # B5: escape pipes, keep FULL values (no 40-char truncation), and surface the
    # per-entity citation that previously only reached report.html.
    entity_rows = ""
    for e in entity_table[:100]:
        cite = e.get('citation') or e.get('source', '')
        conf_disp = _conf_human(e['confidence']) if e.get('confidence') else ''
        entity_rows += (f"| `{_md_cell(e.get('value', ''))}` | {_md_cell(e.get('type', ''))} "
                        f"| {_md_cell(e.get('source', ''))} | {_md_cell(conf_disp)} "
                        f"| {_md_cell(e.get('depth', ''))} | {_md_cell(cite)} |\n")

    # B5: render the relationship table in report.md too (was report.html-only).
    rel_rows = ""
    for r in (relationships or [])[:100]:
        rconf_disp = _conf_human(r['confidence']) if r.get('confidence') else ''
        rel_rows += (f"| {_md_cell(r.get('source', '?'))} | {_md_cell(r.get('relationship', ''))} "
                     f"| {_md_cell(r.get('target', '?'))} | {_md_cell(r.get('source_tool', ''))} "
                     f"| {_md_cell(rconf_disp)} | {_md_cell(r.get('citation', ''))} |\n")

    report = f"""# Cyber Threat Intelligence Report

| Field | Value |
|-------|-------|
| **Case ID** | {case_id} |
| **Classification** | TLP:CLEAR |
| **Date** | {now} |
| **Initial Seed** | `{seed_value}` ({seed_type}) |

---

## BLUF (Bottom Line Up Front)

{bluf}

---

## Significant Findings

{findings_md if findings_md else "No significant findings to report."}

---

## Investigation Method

- **Initial Seed:** `{seed_value}` (type: {seed_type})
- **Tools Used:** {', '.join(tools_used) if tools_used else 'None'}
- **Total Entities Discovered:** {total_entities}
- **Total Relationships Mapped:** {total_relationships}
- **Investigation Duration:** ~{duration_minutes} minutes

### Pivot Chain Summary

{investigation_log_summary}

---

## Entity Summary

| Entity | Type | Source | Confidence | Depth | Citation |
|--------|------|--------|------------|-------|----------|
{entity_rows if entity_rows else "| (none) | - | - | - | - | - |"}

---

## Relationship Map

| Source | Relationship | Target | Tool | Confidence | Citation |
|--------|--------------|--------|------|------------|----------|
{rel_rows if rel_rows else "| (no relationships recorded) | - | - | - | - | - |"}

[Open Interactive Graph](./graph.html)

---

## Implications

{implications if implications else "No implications assessed - insufficient data or investigation scope."}

---

*Generated by OSINT Investigator | Case: {case_id} | {now}*
*This report contains only findings supported by tool output evidence. No speculative analysis included.*
"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    return output_path
